### ISSUE TITLE
Support for viewing FIDO2 resident SSH keys

### ISSUE THREAD

**Issue by e-zk** [Zanthed/yubioath-android#1]
Currently there seems to be a total of 0 applications that support importing the resident YubiKey SSH keys onto Android.

I'd like to be able to import or at least view resident SSH keys on the YubiKey. If I knew where to start I'd start working on this feature myself.

If there are more pressing tasks, or this feature is out-of-scope for this project feel free to close this issue.

See here for info about YubiKey FIDO2 resident SSH keys:
- https://developers.yubico.com/SSH/#_fido2
- https://developers.yubico.com/SSH/Securing_SSH_with_FIDO2.html

**Comment by Zanthed** [comment]
I don't think it's possible to import resident keys as the Yubikey is the generating and storing the private key fully. The resident key isn't meant to leave the Yubikey.

Viewing resident keys might be possible and is doable.

**Comment by e-zk** [comment]
Sure that does make sense (because otherwise what would the point of the YubiKey). 

What I was hoping to have is something equivalent to `ssh-add -K`, which "loads resident keys from a FIDO authenticator" for use with OpenSSH.  
The command typically produces an `id_ed25519_sk` public and private key files. I'm not familiar on the details enough to know if this private key is actually the same as the resident key (i doubt it) or something in between, because using it requires the YubiKey to be attached.

**Comment by Zanthed** [comment]
`ssh-add -K` relies on an SSH agent (`ssh-agent`) and a socket to an SSH agent for communication. I'm not aware of any Android implementation existing for that and APIs for raw UNIX sockets do exist but they do not align to the spec.

**Comment by e-zk** [comment]
My mistake, I meant `ssh-keygen -K`, not `ssh-add -K`.

**Comment by Zanthed** [comment]
This would still require an SSH agent which is an entirely different research project.

I don't think this is in scope of the project unless someone finds a way to implement secure and proper SSH agents into Android apps.

**Comment by e-zk** [comment]
@Zanthed 

> This would still require an SSH agent which is an entirely different research project.

I'm fairly certain this is incorrect, having done so myself without a running agent. To clarify: executing `ssh-keygen -K` does not require an agent to be running for it to output a hardware-backed private key file. 

I no issue if this truly is outside the scope of this project.
